DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:358 POST http://localhost:54019/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (1): localhost:54019
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://localhost:54019 "POST /session HTTP/1.1" 200 753
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:380 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"102.0.5005.61","chrome":{"chromedriverVersion":"102.0.5005.27 (df4a85108ffad4dca2c409c52f24df7ec0204b91-refs/branch-heads/5005_22@{#4})","userDataDir":"/tmp/.com.google.Chrome.cChabV"},"goog:chromeOptions":{"debuggerAddress":"localhost:34621"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:virtualAuthenticators":true},"sessionId":"2c532107636520d9f432da6de64da6b3"}} | headers=HTTPHeaderDict({'Content-Length': '753', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:409 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:358 POST http://http://192.168.72.130:4444/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome"}}}
DEBUG    urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (1): http:80
DEBUG    urllib3.util.retry:retry.py:594 Incremented Retry for (url='//192.168.72.130:4444/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c5f78dd60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': //192.168.72.130:4444/wd/hub/session
DEBUG    urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (2): http:80
DEBUG    urllib3.util.retry:retry.py:594 Incremented Retry for (url='//192.168.72.130:4444/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c5f78df40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': //192.168.72.130:4444/wd/hub/session
DEBUG    urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (3): http:80
DEBUG    urllib3.util.retry:retry.py:594 Incremented Retry for (url='//192.168.72.130:4444/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c5f739160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': //192.168.72.130:4444/wd/hub/session
DEBUG    urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (4): http:80