{"uuid": "cd4b69a9-e307-480e-80d6-de5fbde62f71", "children": ["61bb41c3-5c37-4ac5-87f2-fe03f1afc4e6"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.72.130:4444/wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e68ef13a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n", "trace": "  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/mtest/Documents/Developer/Homeworks/Project/conftest.py\", line 63, in browser\n    driver = webdriver.Remote(\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 433, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 344, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 366, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"/home/mtest/Documents/Developer/Homeworks/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1656399411751, "stop": 1656399414566}], "start": 1656399411751, "stop": 1656399415495}